version: 2.1

orbs:
  training-material: zenika/training-material@volatile
  training-resource: zenika-training/training-resource@volatile
  ztraining2strigo: zenika-training/ztraining2strigo@volatile

parameters:
  force-update:
    description: Force an update on manually triggered pipelines
    type: boolean
    default: false

workflows:
  version: 2

  build-and-deploy:
    when:
      not:
        or:
          - equal: [scheduled_pipeline, << pipeline.trigger_source >>]
          - << pipeline.parameters.force-update >>
    jobs:
      - training-material/build
      - training-material/deploy:
          requires:
            - training-material/build
          filters:
            branches:
              only:
                - master
                - main
          context: training-deploy-zenika

  build-and-update:
    when:
      or:
        - and:
            - equal: [scheduled_pipeline, << pipeline.trigger_source >>]
            - equal: ["Weekly Deploy", << pipeline.schedule.name >>]
        - and:
            - equal: [api, << pipeline.trigger_source >>] # 'api' is the value for manual trigger through API or UI
            - << pipeline.parameters.force-update >>
    jobs:
      - training-material/build
      - ztraining2strigo/update:
          requires:
            - training-material/build
          context: strigo-api
      - training-resource/publish:
          name: Publish Slides on Drive
          requires:
            - training-material/build
          source: dist/pdf/Zenika-formation-angular-Slides.pdf
          file-id: 1CyiRK3RNVXJ0MrmWFpm9CgVrCTI9OO1x
          compression-mode: zip
          context: training-deploy-zenika
      - training-resource/publish:
          name: Publish Workbook on Drive
          requires:
            - training-material/build
          source: dist/pdf/Zenika-formation-angular-Workbook.pdf
          file-id: 1_ez91dUN-px9XP5EuD5eP2Z_onZN6eQL
          compression-mode: zip
          context: training-deploy-zenika
      - training-resource/publish:
          name: Publish Exercises on format zip on Drive
          source: Exercises
          file-id: 14LPgxgG4Nyy38w74R4URNtUlqUt07Qor
          compression-mode: zip
          context: training-deploy-zenika
