version: 2.1

orbs:
  training-material: zenika/training-material@volatile
  ztraining2strigo: zenika-training/ztraining2strigo@volatile

workflows:
  version: 2

  build-and-deploy:
    jobs:
      - training-material/build
      - training-material/deploy:
          requires:
            - training-material/build
          filters:
            branches:
              only:
                - master
                - main
          context: training-deploy-zenika

  build-and-update:
    triggers:
      - schedule:
          cron: "0 0 * * 6"
          filters:
            branches:
              only:
                - wait-for-strigo-fix
    jobs:
      - training-material/build
      - ztraining2strigo/update:
          requires:
            - training-material/build
          context: strigo-api
